//*****************************************************************************************/
//**************************AUTHOR: Mohamed Hesham Hassan***********************//
//**********************************DATE: 01.04.2024**********************************//
//****************************CONTACT: +201115581391*****************************//
//************************EMAIL: mohamedhassan5401@outlook.com****************//
//************************DRIVER: DC Motor Driver ******** *************************//
//***********************************VERSION: 0.0.1**********************************//
//*******************************FILE: USS_CONFIG.H***************** **************//
//************************************************************************************/
#include "BIT_MATH.H"
#include "STD_TYPES.H"
#include "AT_REG.H"  //this file is written by me to include all essential uncategorized addresses
#include <util/delay.h>

#include "GPIO_CONFIG.H"
#include "GPIO_INTERFACE.H"
#include "GPIO_PRIVATE.H"

#include "DCMTR_CONFIG.H"
#include "DCMTR_PRIVATE.H"
#include "DCMTR_INTERFACE.H"


void DCMTR_vInit()
{
    #if  DCMTR_WD_TYPE == DCMTR_CAR_4WD

    SET_BIT(DCMTR_FRONT_LEFT_EN_DDR , DCMTR_FRONT_LEFT_EN_PIN);
    SET_BIT(DCMTR_FRONT_LEFT_A_DDR , DCMTR_FRONT_LEFT_A_PIN);
     SET_BIT(DCMTR_FRONT_LEFT_B_DDR , DCMTR_FRONT_LEFT_B_PIN);

    SET_BIT(DCMTR_FRONT_RIGHT_EN_DDR , DCMTR_FRONT_RIGHT_EN_PIN);
    SET_BIT(DCMTR_FRONT_RIGHT_A_DDR , DCMTR_FRONT_RIGHT_A_PIN);
    SET_BIT(DCMTR_FRONT_RIGHT_B_DDR , DCMTR_FRONT_RIGHT_B_PIN);

    #endif

    SET_BIT(DCMTR_BACK_LEFT_EN_DDR , DCMTR_BACK_LEFT_EN_PIN);
    SET_BIT(DCMTR_BACK_LEFT_A_DDR , DCMTR_BACK_LEFT_A_PIN);
    SET_BIT(DCMTR_BACK_LEFT_B_DDR , DCMTR_BACK_LEFT_B_PIN);

    SET_BIT(DCMTR_BACK_RIGHT_EN_DDR , DCMTR_BACK_RIGHT_EN_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_A_DDR , DCMTR_BACK_RIGHT_A_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_B_DDR , DCMTR_BACK_RIGHT_B_PIN);
}




void DCMTR_MOVE_FORWARD()
{
    SET_BIT(DCMTR_FRONT_LEFT_EN_PORT , DCMTR_FRONT_LEFT_EN_PIN);
    SET_BIT(DCMTR_FRONT_RIGHT_EN_PORT , DCMTR_FRONT_RIGHT_EN_PIN);
    SET_BIT(DCMTR_BACK_LEFT_EN_PORT , DCMTR_BACK_LEFT_EN_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_EN_PORT , DCMTR_BACK_RIGHT_EN_PIN);

    
    CLEAR_BIT(DCMTR_FRONT_LEFT_B_PORT , DCMTR_FRONT_LEFT_B_PIN);
    CLEAR_BIT(DCMTR_FRONT_RIGHT_B_PORT , DCMTR_FRONT_RIGHT_B_PIN);
    CLEAR_BIT(DCMTR_BACK_LEFT_B_PORT , DCMTR_BACK_LEFT_B_PIN);
    CLEAR_BIT(DCMTR_BACK_RIGHT_B_PORT , DCMTR_BACK_RIGHT_B_PIN);


  //DCMTR_SEND_PWM(DCMTR_FRONT_LEFT_A_PORT , DCMTR_FRONT_LEFT_A_PIN );
  //DCMTR_SEND_PWM(DCMTR_FRONT_RIGHT_B_PORT , DCMTR_FRONT_RIGHT_A_PIN );

    SET_BIT(DCMTR_FRONT_LEFT_A_PORT , DCMTR_FRONT_LEFT_A_PIN );
    SET_BIT(DCMTR_FRONT_RIGHT_A_PORT , DCMTR_FRONT_RIGHT_A_PIN );
    SET_BIT(DCMTR_BACK_LEFT_A_PORT , DCMTR_BACK_LEFT_A_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_A_PORT , DCMTR_BACK_RIGHT_A_PIN);
    
    /*_delay_ms(18);
    CLEAR_BIT(DCMTR_FRONT_LEFT_A_PORT , DCMTR_FRONT_LEFT_A_PIN );
    CLEAR_BIT(DCMTR_FRONT_RIGHT_A_PORT , DCMTR_FRONT_RIGHT_A_PIN );
    CLEAR_BIT(DCMTR_BACK_LEFT_A_PORT , DCMTR_BACK_LEFT_A_PIN);
    CLEAR_BIT(DCMTR_BACK_RIGHT_A_PORT , DCMTR_BACK_RIGHT_A_PIN);
    _delay_ms(2);*/

}

void DCMTR_MOVE_BACKWARD()
{
    SET_BIT(DCMTR_FRONT_LEFT_EN_PORT , DCMTR_FRONT_LEFT_EN_PIN);
    SET_BIT(DCMTR_FRONT_RIGHT_EN_PORT , DCMTR_FRONT_RIGHT_EN_PIN);
    SET_BIT(DCMTR_BACK_LEFT_EN_PORT , DCMTR_BACK_LEFT_EN_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_EN_PORT , DCMTR_BACK_RIGHT_EN_PIN);

    
    CLEAR_BIT(DCMTR_FRONT_LEFT_A_PORT , DCMTR_FRONT_LEFT_A_PIN);
    CLEAR_BIT(DCMTR_FRONT_RIGHT_A_PORT , DCMTR_FRONT_RIGHT_A_PIN);
    CLEAR_BIT(DCMTR_BACK_LEFT_A_PORT , DCMTR_BACK_LEFT_A_PIN);
    CLEAR_BIT(DCMTR_BACK_RIGHT_A_PORT , DCMTR_BACK_RIGHT_A_PIN);


  //DCMTR_SEND_PWM(DCMTR_FRONT_LEFT_A_PORT , DCMTR_FRONT_LEFT_A_PIN );
  //DCMTR_SEND_PWM(DCMTR_FRONT_RIGHT_B_PORT , DCMTR_FRONT_RIGHT_A_PIN );

    SET_BIT(DCMTR_FRONT_LEFT_B_PORT , DCMTR_FRONT_LEFT_B_PIN );
    SET_BIT(DCMTR_FRONT_RIGHT_B_PORT , DCMTR_FRONT_RIGHT_B_PIN );
    SET_BIT(DCMTR_BACK_LEFT_B_PORT , DCMTR_BACK_LEFT_B_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_B_PORT , DCMTR_BACK_RIGHT_B_PIN);
    /*_delay_ms(11);
    CLEAR_BIT(DCMTR_FRONT_LEFT_B_PORT , DCMTR_FRONT_LEFT_B_PIN );
    CLEAR_BIT(DCMTR_FRONT_RIGHT_B_PORT , DCMTR_FRONT_RIGHT_B_PIN );
    CLEAR_BIT(DCMTR_BACK_LEFT_B_PORT , DCMTR_BACK_LEFT_B_PIN);
    CLEAR_BIT(DCMTR_BACK_RIGHT_B_PORT , DCMTR_BACK_RIGHT_B_PIN);
    _delay_ms(1);*/

}

void DCMTR_ROTATE_RIGHT()
{
    SET_BIT(DCMTR_FRONT_LEFT_EN_PORT , DCMTR_FRONT_LEFT_EN_PIN);
    SET_BIT(DCMTR_FRONT_RIGHT_EN_PORT , DCMTR_FRONT_RIGHT_EN_PIN);
    SET_BIT(DCMTR_BACK_LEFT_EN_PORT , DCMTR_BACK_LEFT_EN_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_EN_PORT , DCMTR_BACK_RIGHT_EN_PIN);
/**************************************************************************/
    
    CLEAR_BIT(DCMTR_FRONT_LEFT_B_PORT , DCMTR_FRONT_LEFT_B_PIN);
    CLEAR_BIT(DCMTR_BACK_LEFT_B_PORT , DCMTR_BACK_LEFT_B_PIN);

        SET_BIT(DCMTR_FRONT_RIGHT_B_PORT , DCMTR_FRONT_RIGHT_B_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_B_PORT , DCMTR_BACK_RIGHT_B_PIN);


    CLEAR_BIT(DCMTR_FRONT_RIGHT_A_PORT , DCMTR_FRONT_RIGHT_A_PIN );
    CLEAR_BIT(DCMTR_BACK_RIGHT_A_PORT , DCMTR_BACK_RIGHT_A_PIN);

    SET_BIT(DCMTR_FRONT_LEFT_A_PORT , DCMTR_FRONT_LEFT_A_PIN );
    SET_BIT(DCMTR_BACK_LEFT_A_PORT , DCMTR_BACK_LEFT_A_PIN);

_delay_ms(50);
DCMTR_STOP();
}

void DCMTR_ROTATE_LEFT()
{
    SET_BIT(DCMTR_FRONT_LEFT_EN_PORT , DCMTR_FRONT_LEFT_EN_PIN);
    SET_BIT(DCMTR_FRONT_RIGHT_EN_PORT , DCMTR_FRONT_RIGHT_EN_PIN);
    SET_BIT(DCMTR_BACK_LEFT_EN_PORT , DCMTR_BACK_LEFT_EN_PIN);
    SET_BIT(DCMTR_BACK_RIGHT_EN_PORT , DCMTR_BACK_RIGHT_EN_PIN);
/**************************************************************************/
    
    SET_BIT(DCMTR_FRONT_LEFT_B_PORT , DCMTR_FRONT_LEFT_B_PIN);
    SET_BIT(DCMTR_BACK_LEFT_B_PORT , DCMTR_BACK_LEFT_B_PIN);

        CLEAR_BIT(DCMTR_FRONT_RIGHT_B_PORT , DCMTR_FRONT_RIGHT_B_PIN);
    CLEAR_BIT(DCMTR_BACK_RIGHT_B_PORT , DCMTR_BACK_RIGHT_B_PIN);


    SET_BIT(DCMTR_FRONT_RIGHT_A_PORT , DCMTR_FRONT_RIGHT_A_PIN );
    SET_BIT(DCMTR_BACK_RIGHT_A_PORT , DCMTR_BACK_RIGHT_A_PIN);

    CLEAR_BIT(DCMTR_FRONT_LEFT_A_PORT , DCMTR_FRONT_LEFT_A_PIN );
    CLEAR_BIT(DCMTR_BACK_LEFT_A_PORT , DCMTR_BACK_LEFT_A_PIN);

_delay_ms(50);
DCMTR_STOP();
}


void DCMTR_STOP()
{
         CLEAR_BIT(DCMTR_FRONT_LEFT_EN_PORT , DCMTR_FRONT_LEFT_EN_PIN);
         CLEAR_BIT(DCMTR_FRONT_RIGHT_EN_PORT , DCMTR_FRONT_RIGHT_EN_PIN);
        CLEAR_BIT(DCMTR_BACK_LEFT_EN_PORT , DCMTR_BACK_LEFT_EN_PIN);
         CLEAR_BIT(DCMTR_BACK_RIGHT_EN_PORT , DCMTR_BACK_RIGHT_EN_PIN);

}
