//*****************************************************************************************/
//**************************AUTHOR: Mohamed Hesham Hassan***********************//
//**********************************DATE: 16.02.2024**********************************//
//****************************CONTACT: +201115581391*****************************//
//************************EMAIL: mohamedhassan5401@outlook.com****************//
//************************DRIVER: LCD; Liqiud Crystal Display Module ***************//
//***********************************VERSION: 0.0.1**********************************//
//*******************************FILE: LCD_PRIVATE.H*******************************//
//*************************************************************************************/

#ifndef LCD_PRIVATE_H 
// Header guard . (if file is not defined then define it)
#define LCD_PRIVATE_H

#define LCD_DB0 0
#define LCD_DB1 1
#define LCD_DB2 2
#define LCD_DB3 3
#define LCD_DB4 4
#define LCD_DB5 5
#define LCD_DB6 6
#define LCD_DB7 7

#define LCD_BF 7

#endif